In [24]:
%pip install pandas numpy

Requirement already satisfied: pandas in c:\users\30479\appdata\local\programs\python\python314\lib\site-packages (3.0.1)
Requirement already satisfied: numpy in c:\users\30479\appdata\local\programs\python\python314\lib\site-packages (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\30479\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\30479\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\30479\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
import pandas as pd
import numpy as np
#导入健康数据汇总csv
df=pd.read_csv('D:/DA/Huawei_Sleep_Analysis/DATA/processed/health_daily_summary.csv')
#预览数据前五行
df.head()

,日期,REM时长,午睡时长,浅睡时长,深睡时长,清醒时长,夜间总睡眠,在床时间,睡眠效率,深睡比例,...,是否午睡,星期,总步数,总消耗,总时长,每公里消耗,平均心率,最小心率,最大心率,记录条数
0,2025-06-20,134.0,60.0,248.0,151.0,28.0,8.88,561.0,95.01,28.33,...,True,周五,14404,256.22,180,20.32,80.47,44,188,535
1,2025-06-21,80.0,56.0,161.0,88.0,18.0,5.48,347.0,94.81,26.75,...,True,周六,15735,155.27,141,10.52,94.21,40,166,633
2,2025-06-22,156.0,66.0,260.0,116.0,16.0,8.87,548.0,97.08,21.80,...,True,周日,13205,147.29,163,9.87,75.62,42,154,481
3,2025-06-23,61.0,59.0,227.0,85.0,15.0,6.22,388.0,96.13,22.79,...,True,周一,3138,40.48,74,16.29,80.84,41,177,600
4,2025-06-24,116.0,54.0,302.0,117.0,17.0,8.92,552.0,96.92,21.87,...,True,周二,14790,137.85,129,10.09,77.53,36,176,478

In [26]:
df.isnull().sum()

日期        0
REM时长     3
午睡时长      3
浅睡时长      3
深睡时长      3
清醒时长      3
夜间总睡眠     3
在床时间      3
睡眠效率      5
深睡比例      5
浅睡比例      5
快速眼动比例    5
是否午睡      3
星期        0
总步数       0
总消耗       0
总时长       0
每公里消耗     0
平均心率      0
最小心率      0
最大心率      0
记录条数      0
dtype: int64

In [27]:
#用各列的平均值填充缺失值
df['REM时长']=df['REM时长'].fillna(df['REM时长'].mean())
df['REM时长']=df['REM时长'].round(1)

df['午睡时长']=df['午睡时长'].fillna(df['午睡时长'].mean())
df['午睡时长']=df['午睡时长'].round(1)

df['深睡时长']=df['深睡时长'].fillna(df['深睡时长'].mean())
df['深睡时长']=df['深睡时长'].round(1)

df['浅睡时长']=df['浅睡时长'].fillna(df['浅睡时长'].mean())
df['浅睡时长']=df['浅睡时长'].round(1)

df['睡眠效率']=df['睡眠效率'].fillna(df['睡眠效率'].mean())
df['睡眠效率']=df['睡眠效率'].round(2)

df['清醒时长']=df['清醒时长'].fillna(df['清醒时长'].mean())
df['清醒时长']=df['清醒时长'].round(1)

df['夜间总睡眠']=df['夜间总睡眠'].fillna(df['夜间总睡眠'].mean())
df['夜间总睡眠']=df['夜间总睡眠'].round(2)

df['深睡比例']=df['深睡比例'].fillna(df['深睡比例'].mean())
df['深睡比例']=df['深睡比例'].round(2)

df['浅睡比例']=df['浅睡比例'].fillna(df['浅睡比例'].mean())
df['浅睡比例']=df['浅睡比例'].round(2)

df['快速眼动比例']=df['快速眼动比例'].fillna(df['快速眼动比例'].mean())
df['快速眼动比例']=df['快速眼动比例'].round(2)

df['在床时间']=df['在床时间'].fillna(df['在床时间'].mean())
df['在床时间']=df['在床时间'].round(1)

df['总时长']=df['总时长'].fillna(df['总时长'].mean())
df['总时长']=df['总时长'].round(1)

df['总步数']=df['总步数'].fillna(df['总步数'].mean())
df['总步数']=df['总步数'].round(1)

df['总消耗']=df['总消耗'].fillna(df['总消耗'].mean())
df['总消耗']=df['总消耗'].round(1)

df['每公里消耗']=df['每公里消耗'].fillna(df['每公里消耗'].mean())
df['每公里消耗']=df['每公里消耗'].round(1)

#用该列第一个众数填充缺失值
df['是否午睡']=df['是否午睡'].fillna(df['是否午睡'].mode()[0])

df['星期']=df['星期'].fillna(df['星期'].mode()[0])

df.isnull().sum()

日期        0
REM时长     0
午睡时长      0
浅睡时长      0
深睡时长      0
清醒时长      0
夜间总睡眠     0
在床时间      0
睡眠效率      0
深睡比例      0
浅睡比例      0
快速眼动比例    0
是否午睡      0
星期        0
总步数       0
总消耗       0
总时长       0
每公里消耗     0
平均心率      0
最小心率      0
最大心率      0
记录条数      0
dtype: int64

In [28]:
#查询重复列
dup=df.duplicated().sum()
print(dup)

0

In [29]:
#查看各字段基础统计值，查看极端值是否合理
df.describe()

,REM时长,午睡时长,浅睡时长,深睡时长,清醒时长,夜间总睡眠,在床时间,睡眠效率,深睡比例,浅睡比例,快速眼动比例,总步数,总消耗,总时长,每公里消耗,平均心率,最小心率,最大心率,记录条数
count,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000
mean,73.171841,44.361733,250.795668,110.003610,27.594946,7.232996,461.566065,94.036787,25.295199,58.011805,16.692780,5288.061372,53.646931,97.631769,15.066787,77.758845,42.967509,151.859206,638.342960
std,25.699838,40.906452,60.767571,36.895907,18.659422,1.536718,96.896092,3.763724,6.547037,7.916818,4.098427,4562.033867,57.420220,55.597103,10.851844,10.369449,3.238529,26.694698,96.823357
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,73.850000,6.020000,33.480000,5.320000,369.000000,0.700000,15.000000,2.100000,58.160000,36.000000,95.000000,273.000000
25%,55.000000,0.000000,213.000000,85.000000,16.000000,6.230000,398.000000,92.970000,21.090000,52.780000,14.010000,1440.000000,14.100000,50.000000,7.400000,71.420000,40.000000,131.000000,583.000000
50%,73.000000,42.000000,250.800000,110.000000,22.000000,7.330000,467.000000,94.830000,25.260000,58.010000,16.690000,3967.000000,30.400000,92.000000,11.900000,76.650000,43.000000,156.000000,634.000000
75%,89.000000,62.000000,294.000000,134.000000,33.000000,8.280000,539.000000,96.470000,29.200000,63.340000,19.240000,8195.000000,84.800000,135.000000,19.500000,83.190000,46.000000,175.000000,686.000000
max,156.000000,238.000000,388.000000,222.000000,110.000000,10.750000,661.000000,99.360000,43.720000,78.670000,29.320000,30945.000000,484.800000,416.000000,61.200000,118.530000,51.000000,191.000000,1077.000000

In [30]:
#处理异常值
df['REM时长']=df['REM时长'].replace(0,np.nan)

df['浅睡时长']=df['浅睡时长'].replace(0,np.nan)

df['深睡时长']=df['深睡时长'].replace(0,np.nan)

df['夜间总睡眠']=df['夜间总睡眠'].replace(0,np.nan)

df['在床时间']=df['在床时间'].replace(0,np.nan)

#再次查看基础统计值
df.describe()

,REM时长,午睡时长,浅睡时长,深睡时长,清醒时长,夜间总睡眠,在床时间,睡眠效率,深睡比例,浅睡比例,快速眼动比例,总步数,总消耗,总时长,每公里消耗,平均心率,最小心率,最大心率,记录条数
count,275.000000,277.000000,275.000000,275.000000,277.000000,275.000000,275.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000
mean,73.704000,44.361733,252.619636,110.803636,27.594946,7.285600,464.922909,94.036787,25.295199,58.011805,16.692780,5288.061372,53.646931,97.631769,15.066787,77.758845,42.967509,151.859206,638.342960
std,25.018739,40.906452,57.071882,35.808870,18.659422,1.412123,88.831384,3.763724,6.547037,7.916818,4.098427,4562.033867,57.420220,55.597103,10.851844,10.369449,3.238529,26.694698,96.823357
min,12.000000,0.000000,59.000000,8.000000,0.000000,1.570000,102.000000,73.850000,6.020000,33.480000,5.320000,369.000000,0.700000,15.000000,2.100000,58.160000,36.000000,95.000000,273.000000
25%,55.000000,0.000000,213.000000,85.500000,16.000000,6.260000,401.500000,92.970000,21.090000,52.780000,14.010000,1440.000000,14.100000,50.000000,7.400000,71.420000,40.000000,131.000000,583.000000
50%,73.000000,42.000000,251.000000,110.000000,22.000000,7.350000,467.000000,94.830000,25.260000,58.010000,16.690000,3967.000000,30.400000,92.000000,11.900000,76.650000,43.000000,156.000000,634.000000
75%,89.000000,62.000000,294.000000,134.000000,33.000000,8.315000,539.000000,96.470000,29.200000,63.340000,19.240000,8195.000000,84.800000,135.000000,19.500000,83.190000,46.000000,175.000000,686.000000
max,156.000000,238.000000,388.000000,222.000000,110.000000,10.750000,661.000000,99.360000,43.720000,78.670000,29.320000,30945.000000,484.800000,416.000000,61.200000,118.530000,51.000000,191.000000,1077.000000

In [33]:
#再次查看缺失值情况
df.isnull().sum()

日期        0
REM时长     2
午睡时长      0
浅睡时长      2
深睡时长      2
清醒时长      0
夜间总睡眠     2
在床时间      2
睡眠效率      0
深睡比例      0
浅睡比例      0
快速眼动比例    0
是否午睡      0
星期        0
总步数       0
总消耗       0
总时长       0
每公里消耗     0
平均心率      0
最小心率      0
最大心率      0
记录条数      0
dtype: int64

In [34]:
#再次填充空缺值
df['REM时长']=df['REM时长'].fillna(df['REM时长'].mean())
df['REM时长']=df['REM时长'].round(1)

df['深睡时长']=df['深睡时长'].fillna(df['深睡时长'].mean())
df['深睡时长']=df['深睡时长'].round(1)

df['浅睡时长']=df['浅睡时长'].fillna(df['浅睡时长'].mean())
df['浅睡时长']=df['浅睡时长'].round(1)

df['夜间总睡眠']=df['夜间总睡眠'].fillna(df['夜间总睡眠'].mean())
df['夜间总睡眠']=df['夜间总睡眠'].round(2)

df['在床时间']=df['在床时间'].fillna(df['在床时间'].mean())
df['在床时间']=df['在床时间'].round(1)

In [35]:

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 22 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   日期      277 non-null    str
 1   REM时长   277 non-null    float64
 2   午睡时长    277 non-null    float64
 3   浅睡时长    277 non-null    float64
 4   深睡时长    277 non-null    float64
 5   清醒时长    277 non-null    float64
 6   夜间总睡眠   277 non-null    float64
 7   在床时间    277 non-null    float64
 8   睡眠效率    277 non-null    float64
 9   深睡比例    277 non-null    float64
 10  浅睡比例    277 non-null    float64
 11  快速眼动比例  277 non-null    float64
 12  是否午睡    277 non-null    object
 13  星期      277 non-null    str
 14  总步数     277 non-null    int64
 15  总消耗     277 non-null    float64
 16  总时长     277 non-null    int64
 17  每公里消耗   277 non-null    float64
 18  平均心率    277 non-null    float64
 19  最小心率    277 non-null    int64
 20  最大心率    277 non-null    int64
 21  记录条数    277 non-null    int64
dtypes: float64(14), int64(5), object(1), str(2)
memory usage: 47.7+ KB

In [36]:
#导出清洗后的数据
df.to_csv('D:/DA/Huawei_Sleep_Analysis/DATA/processed/health_daily_summary_cleaned.csv',index=False,encoding='utf-8-sig')