In [ ]:
%pip install pandas numpy

Requirement already satisfied: pandas in c:\users\30479\appdata\local\programs\python\python314\lib\site-packages (3.0.1)
Requirement already satisfied: numpy in c:\users\30479\appdata\local\programs\python\python314\lib\site-packages (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\30479\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\30479\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\30479\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd
import numpy as np
#导入健康数据汇总csv
df=pd.read_csv('D:/DA/Huawei_Health_Analysis/DATA/processed/health_daily_summary.csv')
#预览数据前五行
df.head()

,日期,REM时长,午睡时长,浅睡时长,深睡时长,清醒时长,夜间总睡眠,在床时间,睡眠效率,深睡比例,...,星期,总步数,总时长,基础代谢,活动消耗,全天总消耗,平均心率,最小心率,最大心率,记录条数
0,2025-05-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,周日,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
1,2025-05-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,周一,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
2,2025-05-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,周二,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
3,2025-05-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,周三,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
4,2025-05-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,周四,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN

In [ ]:
df.isnull().sum()

日期          0
REM时长      36
午睡时长       36
浅睡时长       36
深睡时长       36
清醒时长       36
夜间总睡眠      36
在床时间       36
睡眠效率       38
深睡比例       38
浅睡比例       38
快速眼动比例     38
是否午睡       36
星期          0
总步数         6
总时长         6
基础代谢      165
活动消耗        0
全天总消耗       0
平均心率        6
最小心率        6
最大心率        6
记录条数        6
dtype: int64

In [ ]:
#用各列的中位数填充缺失值
df['REM时长']=df['REM时长'].fillna(df['REM时长'].median())
df['REM时长']=df['REM时长'].round(1)

df['午睡时长']=df['午睡时长'].fillna(df['午睡时长'].median())
df['午睡时长']=df['午睡时长'].round(1)

df['深睡时长']=df['深睡时长'].fillna(df['深睡时长'].median())
df['深睡时长']=df['深睡时长'].round(1)

df['浅睡时长']=df['浅睡时长'].fillna(df['浅睡时长'].median())
df['浅睡时长']=df['浅睡时长'].round(1)

df['睡眠效率']=df['睡眠效率'].fillna(df['睡眠效率'].median())
df['睡眠效率']=df['睡眠效率'].round(2)

df['清醒时长']=df['清醒时长'].fillna(df['清醒时长'].median())
df['清醒时长']=df['清醒时长'].round(1)

df['夜间总睡眠']=df['夜间总睡眠'].fillna(df['夜间总睡眠'].median())
df['夜间总睡眠']=df['夜间总睡眠'].round(2)

df['深睡比例']=df['深睡比例'].fillna(df['深睡比例'].median())
df['深睡比例']=df['深睡比例'].round(2)

df['浅睡比例']=df['浅睡比例'].fillna(df['浅睡比例'].median())
df['浅睡比例']=df['浅睡比例'].round(2)

df['快速眼动比例']=df['快速眼动比例'].fillna(df['快速眼动比例'].median())
df['快速眼动比例']=df['快速眼动比例'].round(2)

df['在床时间']=df['在床时间'].fillna(df['在床时间'].median())
df['在床时间']=df['在床时间'].round(1)

df['总时长']=df['总时长'].fillna(df['总时长'].median())
df['总时长']=df['总时长'].round(1)

df['总步数']=df['总步数'].fillna(df['总步数'].median())
df['总步数']=df['总步数'].round(1)

df['基础代谢']=df['基础代谢'].fillna(df['基础代谢'].median())
df['基础代谢']=df['基础代谢'].round(1)

df['平均心率']=df['平均心率'].fillna(df['平均心率'].median())
df['平均心率']=df['平均心率'].round(2)

df['最大心率']=df['最大心率'].fillna(df['最大心率'].median())
df['最大心率']=df['最大心率'].round(1)

df['最小心率']=df['最小心率'].fillna(df['最小心率'].median())
df['最小心率']=df['最小心率'].round(1)

df['记录条数']=df['记录条数'].fillna(df['记录条数'].median())
df['记录条数']=df['记录条数'].round(1)

#用该列第一个众数填充缺失值
df['是否午睡']=df['是否午睡'].fillna(df['是否午睡'].mode()[0])

df['星期']=df['星期'].fillna(df['星期'].mode()[0])

df.isnull().sum()

日期        0
REM时长     0
午睡时长      0
浅睡时长      0
深睡时长      0
清醒时长      0
夜间总睡眠     0
在床时间      0
睡眠效率      0
深睡比例      0
浅睡比例      0
快速眼动比例    0
是否午睡      0
星期        0
总步数       0
总时长       0
基础代谢      0
活动消耗      0
全天总消耗     0
平均心率      0
最小心率      0
最大心率      0
记录条数      0
dtype: int64

In [ ]:
#查询重复列
dup=df.duplicated().sum()
print(dup)

0

In [ ]:
#查看各字段基础统计值，查看极端值是否合理
df.describe()

,REM时长,午睡时长,浅睡时长,深睡时长,清醒时长,夜间总睡眠,在床时间,睡眠效率,深睡比例,浅睡比例,快速眼动比例,总步数,总时长,基础代谢,活动消耗,全天总消耗,平均心率,最小心率,最大心率,记录条数
count,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000
mean,73.125402,43.829582,251.125402,109.781350,27.244373,7.245595,463.012862,94.085723,25.226527,58.075691,16.690257,5641.270096,98.276527,1833.884244,588.356817,1449.218585,77.949839,42.803859,152.601286,631.212219
std,24.254039,38.693501,57.437430,35.033032,18.467358,1.450595,91.583418,3.683085,6.239332,7.528467,3.867629,5349.099583,57.842451,13.119037,597.687279,1053.141909,10.387707,3.202336,26.619333,106.294842
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,73.850000,6.020000,33.480000,5.320000,39.000000,2.000000,1771.000000,0.000000,0.000000,58.160000,36.000000,94.000000,196.000000
25%,57.000000,13.000000,217.500000,87.500000,17.000000,6.425000,406.500000,93.135000,21.605000,53.570000,14.365000,1590.000000,50.500000,1834.000000,186.520000,440.310000,71.665000,40.000000,132.500000,570.000000
50%,73.000000,41.000000,252.000000,110.000000,22.000000,7.350000,472.000000,94.870000,25.140000,58.100000,16.700000,4136.000000,93.000000,1834.000000,453.380000,1736.000000,76.910000,43.000000,158.000000,631.000000
75%,87.500000,58.500000,290.000000,129.500000,31.000000,8.250000,533.500000,96.305000,28.555000,61.950000,18.920000,8606.000000,134.000000,1834.000000,782.230000,2277.290000,83.010000,45.000000,175.000000,685.000000
max,156.000000,238.000000,388.000000,222.000000,120.000000,10.750000,661.000000,99.360000,43.720000,78.670000,29.320000,47298.000000,431.000000,1863.000000,3913.440000,5236.540000,118.530000,51.000000,191.000000,1149.000000

In [ ]:
#处理异常值
df['REM时长']=df['REM时长'].replace(0,np.nan)

df['浅睡时长']=df['浅睡时长'].replace(0,np.nan)

df['深睡时长']=df['深睡时长'].replace(0,np.nan)

df['夜间总睡眠']=df['夜间总睡眠'].replace(0,np.nan)

df['在床时间']=df['在床时间'].replace(0,np.nan)

df['活动消耗']=df['活动消耗'].replace(0,np.nan)

df['全天总消耗']=df['全天总消耗'].replace(0,np.nan)
#再次查看基础统计值
df.describe()

,REM时长,午睡时长,浅睡时长,深睡时长,清醒时长,夜间总睡眠,在床时间,睡眠效率,深睡比例,浅睡比例,快速眼动比例,总步数,总时长,基础代谢,活动消耗,全天总消耗,平均心率,最小心率,最大心率,记录条数
count,309.000000,311.000000,309.000000,309.000000,311.000000,309.000000,309.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,305.000000,305.000000,311.000000,311.000000,311.000000,311.000000
mean,73.598706,43.829582,252.750809,110.491909,27.244373,7.292492,466.009709,94.085723,25.226527,58.075691,16.690257,5641.270096,98.276527,1833.884244,599.931049,1477.727803,77.949839,42.803859,152.601286,631.212219
std,23.603615,38.693501,53.928880,34.007602,18.467358,1.332210,83.910028,3.683085,6.239332,7.528467,3.867629,5349.099583,57.842451,13.119037,597.757555,1043.422600,10.387707,3.202336,26.619333,106.294842
min,12.000000,0.000000,59.000000,8.000000,0.000000,1.570000,102.000000,73.850000,6.020000,33.480000,5.320000,39.000000,2.000000,1771.000000,12.410000,12.410000,58.160000,36.000000,94.000000,196.000000
25%,58.000000,13.000000,219.000000,88.000000,17.000000,6.450000,408.000000,93.135000,21.605000,53.570000,14.365000,1590.000000,50.500000,1834.000000,199.900000,472.880000,71.665000,40.000000,132.500000,570.000000
50%,73.000000,41.000000,252.000000,110.000000,22.000000,7.350000,472.000000,94.870000,25.140000,58.100000,16.700000,4136.000000,93.000000,1834.000000,456.380000,1863.420000,76.910000,43.000000,158.000000,631.000000
75%,88.000000,58.500000,290.000000,130.000000,31.000000,8.250000,534.000000,96.305000,28.555000,61.950000,18.920000,8606.000000,134.000000,1834.000000,784.600000,2286.720000,83.010000,45.000000,175.000000,685.000000
max,156.000000,238.000000,388.000000,222.000000,120.000000,10.750000,661.000000,99.360000,43.720000,78.670000,29.320000,47298.000000,431.000000,1863.000000,3913.440000,5236.540000,118.530000,51.000000,191.000000,1149.000000

In [ ]:
#活动消耗和全天总消耗最小值异常，经查2026-03-24当天导出数据时未记录完全整体消耗，删除该日。
df=df.drop(df[df['日期']=='2026-03-24'].index)

In [ ]:
#再次查看缺失值情况
df.isnull().sum()

日期        0
REM时长     2
午睡时长      0
浅睡时长      2
深睡时长      2
清醒时长      0
夜间总睡眠     2
在床时间      2
睡眠效率      0
深睡比例      0
浅睡比例      0
快速眼动比例    0
是否午睡      0
星期        0
总步数       0
总时长       0
基础代谢      0
活动消耗      6
全天总消耗     6
平均心率      0
最小心率      0
最大心率      0
记录条数      0
dtype: int64

In [ ]:
#再次填充空缺值
df['REM时长']=df['REM时长'].fillna(df['REM时长'].median())
df['REM时长']=df['REM时长'].round(1)

df['深睡时长']=df['深睡时长'].fillna(df['深睡时长'].median())
df['深睡时长']=df['深睡时长'].round(1)

df['浅睡时长']=df['浅睡时长'].fillna(df['浅睡时长'].median())
df['浅睡时长']=df['浅睡时长'].round(1)

df['夜间总睡眠']=df['夜间总睡眠'].fillna(df['夜间总睡眠'].median())
df['夜间总睡眠']=df['夜间总睡眠'].round(2)

df['在床时间']=df['在床时间'].fillna(df['在床时间'].median())
df['在床时间']=df['在床时间'].round(1)

df['活动消耗']=df['活动消耗'].fillna(df['活动消耗'].median())
df['活动消耗']=df['活动消耗'].round(2)

df['全天总消耗']=df['全天总消耗'].fillna(df['全天总消耗'].median())
df['全天总消耗']=df['全天总消耗'].round(2)

In [ ]:
#更新缺失基础代谢和活动消耗日期的全天总消耗列，计算方式为基础代谢+活动消耗
df.loc[df['日期']<'2025-11-01','全天总消耗']=round(df['基础代谢']+df['活动消耗'], 1)

In [ ]:
#终核数据是否有异常
df.describe()

,REM时长,午睡时长,浅睡时长,深睡时长,清醒时长,夜间总睡眠,在床时间,睡眠效率,深睡比例,浅睡比例,快速眼动比例,总步数,总时长,基础代谢,活动消耗,全天总消耗,平均心率,最小心率,最大心率,记录条数
count,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000
mean,73.622581,43.970968,252.561290,110.712903,26.945161,7.294032,465.822581,94.138871,25.276097,58.022645,16.693710,5659.341935,98.587097,1833.809677,599.046419,2432.854097,78.001645,42.800000,152.790323,632.616129
std,23.560350,38.675513,53.742655,33.720892,17.726077,1.329899,83.680647,3.567591,6.187779,7.482198,3.873402,5348.230174,57.675668,13.074070,592.328484,593.056182,10.364182,3.206789,26.452459,103.538422
min,12.000000,0.000000,59.000000,8.000000,0.000000,1.570000,102.000000,73.850000,6.020000,33.480000,5.320000,369.000000,15.000000,1771.000000,12.410000,1846.400000,58.160000,36.000000,95.000000,273.000000
25%,58.000000,13.250000,219.250000,88.250000,17.000000,6.450000,408.250000,93.187500,21.615000,53.545000,14.357500,1605.750000,51.250000,1834.000000,212.805000,2038.530000,71.827500,40.000000,133.000000,570.250000
50%,73.000000,41.000000,252.000000,110.000000,22.000000,7.350000,472.000000,94.870000,25.140000,58.100000,16.700000,4136.000000,93.000000,1834.000000,458.540000,2293.565000,76.910000,43.000000,158.000000,631.000000
75%,87.750000,58.750000,289.750000,129.750000,31.000000,8.250000,532.750000,96.307500,28.612500,61.935000,18.940000,8629.500000,134.000000,1834.000000,782.835000,2618.015000,83.075000,45.000000,175.000000,685.000000
max,156.000000,238.000000,388.000000,222.000000,110.000000,10.750000,661.000000,99.360000,43.720000,78.670000,29.320000,47298.000000,431.000000,1863.000000,3913.440000,5747.400000,118.530000,51.000000,191.000000,1149.000000

In [ ]:

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 23 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   日期      310 non-null    str
 1   REM时长   310 non-null    float64
 2   午睡时长    310 non-null    float64
 3   浅睡时长    310 non-null    float64
 4   深睡时长    310 non-null    float64
 5   清醒时长    310 non-null    float64
 6   夜间总睡眠   310 non-null    float64
 7   在床时间    310 non-null    float64
 8   睡眠效率    310 non-null    float64
 9   深睡比例    310 non-null    float64
 10  浅睡比例    310 non-null    float64
 11  快速眼动比例  310 non-null    float64
 12  是否午睡    310 non-null    object
 13  星期      310 non-null    str
 14  总步数     310 non-null    float64
 15  总时长     310 non-null    float64
 16  基础代谢    310 non-null    float64
 17  活动消耗    310 non-null    float64
 18  全天总消耗   310 non-null    float64
 19  平均心率    310 non-null    float64
 20  最小心率    310 non-null    float64
 21  最大心率    310 non-null    float64
 22  记录条数    310 non-null    float64
dtypes: float64(20), object(1), str(2)
memory usage: 55.8+ KB

In [ ]:
#导出清洗后的数据
df.to_csv('D:/DA/Huawei_Health_Analysis/DATA/processed/health_daily_summary_cleaned.csv',index=False,encoding='utf-8-sig')