In [1]:
%pip install pandas numpy

Requirement already satisfied: pandas in c:\users\30479\appdata\local\programs\python\python314\lib\site-packages (3.0.1)
Requirement already satisfied: numpy in c:\users\30479\appdata\local\programs\python\python314\lib\site-packages (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\30479\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\30479\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\30479\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
#导入健康数据汇总csv
df=pd.read_csv('D:/DA/Huawei_Health_Analysis/DATA/processed/health_daily_summary.csv')
#预览数据前五行
df.head()

,日期,REM时长,午睡时长,浅睡时长,深睡时长,清醒时长,夜间总睡眠,在床时间,睡眠效率,深睡比例,...,是否午睡,星期,总步数,总消耗,总时长,每公里消耗,平均心率,最小心率,最大心率,记录条数
0,2025-05-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,周六,1053,4.92,19,6.51,68.43,45,126,342
1,2025-05-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,周日,1894,197.48,160,4.52,95.86,46,168,607
2,2025-05-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,周一,10998,98.88,123,10.51,82.07,47,185,415
3,2025-05-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,周二,9763,90.72,116,10.69,78.13,38,186,628
4,2025-05-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,周三,15446,163.74,138,11.50,78.95,40,186,561

In [3]:
df.isnull().sum()

日期         0
REM时长     30
午睡时长      30
浅睡时长      30
深睡时长      30
清醒时长      30
夜间总睡眠     30
在床时间      30
睡眠效率      32
深睡比例      32
浅睡比例      32
快速眼动比例    32
是否午睡      30
星期         0
总步数        0
总消耗        0
总时长        0
每公里消耗      0
平均心率       0
最小心率       0
最大心率       0
记录条数       0
dtype: int64

In [4]:
#用各列的平均值填充缺失值
df['REM时长']=df['REM时长'].fillna(df['REM时长'].mean())
df['REM时长']=df['REM时长'].round(1)

df['午睡时长']=df['午睡时长'].fillna(df['午睡时长'].mean())
df['午睡时长']=df['午睡时长'].round(1)

df['深睡时长']=df['深睡时长'].fillna(df['深睡时长'].mean())
df['深睡时长']=df['深睡时长'].round(1)

df['浅睡时长']=df['浅睡时长'].fillna(df['浅睡时长'].mean())
df['浅睡时长']=df['浅睡时长'].round(1)

df['睡眠效率']=df['睡眠效率'].fillna(df['睡眠效率'].mean())
df['睡眠效率']=df['睡眠效率'].round(2)

df['清醒时长']=df['清醒时长'].fillna(df['清醒时长'].mean())
df['清醒时长']=df['清醒时长'].round(1)

df['夜间总睡眠']=df['夜间总睡眠'].fillna(df['夜间总睡眠'].mean())
df['夜间总睡眠']=df['夜间总睡眠'].round(2)

df['深睡比例']=df['深睡比例'].fillna(df['深睡比例'].mean())
df['深睡比例']=df['深睡比例'].round(2)

df['浅睡比例']=df['浅睡比例'].fillna(df['浅睡比例'].mean())
df['浅睡比例']=df['浅睡比例'].round(2)

df['快速眼动比例']=df['快速眼动比例'].fillna(df['快速眼动比例'].mean())
df['快速眼动比例']=df['快速眼动比例'].round(2)

df['在床时间']=df['在床时间'].fillna(df['在床时间'].mean())
df['在床时间']=df['在床时间'].round(1)

df['总时长']=df['总时长'].fillna(df['总时长'].mean())
df['总时长']=df['总时长'].round(1)

df['总步数']=df['总步数'].fillna(df['总步数'].mean())
df['总步数']=df['总步数'].round(1)

df['总消耗']=df['总消耗'].fillna(df['总消耗'].mean())
df['总消耗']=df['总消耗'].round(1)

df['每公里消耗']=df['每公里消耗'].fillna(df['每公里消耗'].mean())
df['每公里消耗']=df['每公里消耗'].round(1)

#用该列第一个众数填充缺失值
df['是否午睡']=df['是否午睡'].fillna(df['是否午睡'].mode()[0])

df['星期']=df['星期'].fillna(df['星期'].mode()[0])

df.isnull().sum()

日期        0
REM时长     0
午睡时长      0
浅睡时长      0
深睡时长      0
清醒时长      0
夜间总睡眠     0
在床时间      0
睡眠效率      0
深睡比例      0
浅睡比例      0
快速眼动比例    0
是否午睡      0
星期        0
总步数       0
总消耗       0
总时长       0
每公里消耗     0
平均心率      0
最小心率      0
最大心率      0
记录条数      0
dtype: int64

In [5]:
#查询重复列
dup=df.duplicated().sum()
print(dup)

0

In [6]:
#查看各字段基础统计值，查看极端值是否合理
df.describe()

,REM时长,午睡时长,浅睡时长,深睡时长,清醒时长,夜间总睡眠,在床时间,睡眠效率,深睡比例,浅睡比例,快速眼动比例,总步数,总消耗,总时长,每公里消耗,平均心率,最小心率,最大心率,记录条数
count,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000
mean,73.137705,44.200000,251.009836,109.757377,27.927869,7.231738,461.832787,93.976918,25.238721,58.072066,16.689016,5670.881967,57.237377,98.380328,14.678033,77.970295,42.800000,152.495082,631.216393
std,24.492179,39.059755,58.000595,35.376976,18.549694,1.464342,92.424288,3.707460,6.300519,7.602393,3.905608,5397.406204,61.090353,58.405679,10.475552,10.488679,3.233663,26.869828,107.338675
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,73.850000,6.020000,33.480000,5.320000,39.000000,0.200000,2.000000,2.100000,58.160000,36.000000,94.000000,196.000000
25%,57.000000,13.000000,215.000000,87.000000,16.000000,6.320000,406.000000,93.030000,21.480000,53.430000,14.310000,1566.000000,14.300000,50.000000,7.800000,71.530000,40.000000,132.000000,569.000000
50%,73.100000,44.200000,251.000000,109.800000,24.000000,7.230000,461.800000,94.460000,25.240000,58.070000,16.690000,4136.000000,32.400000,93.000000,11.100000,76.910000,43.000000,158.000000,631.000000
75%,88.000000,59.000000,291.000000,131.000000,32.000000,8.270000,535.000000,96.320000,28.780000,62.420000,19.060000,8757.000000,92.100000,134.000000,18.700000,83.190000,45.000000,175.000000,685.000000
max,156.000000,238.000000,388.000000,222.000000,120.000000,10.750000,661.000000,99.360000,43.720000,78.670000,29.320000,47298.000000,484.800000,431.000000,61.200000,118.530000,51.000000,191.000000,1149.000000

In [7]:
#处理异常值
df['REM时长']=df['REM时长'].replace(0,np.nan)

df['浅睡时长']=df['浅睡时长'].replace(0,np.nan)

df['深睡时长']=df['深睡时长'].replace(0,np.nan)

df['夜间总睡眠']=df['夜间总睡眠'].replace(0,np.nan)

df['在床时间']=df['在床时间'].replace(0,np.nan)

#再次查看基础统计值
df.describe()

,REM时长,午睡时长,浅睡时长,深睡时长,清醒时长,夜间总睡眠,在床时间,睡眠效率,深睡比例,浅睡比例,快速眼动比例,总步数,总消耗,总时长,每公里消耗,平均心率,最小心率,最大心率,记录条数
count,303.000000,305.000000,303.000000,303.000000,305.000000,303.000000,303.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000
mean,73.620462,44.200000,252.666667,110.481848,27.927869,7.279472,464.881188,93.976918,25.238721,58.072066,16.689016,5670.881967,57.237377,98.380328,14.678033,77.970295,42.800000,152.495082,631.216393
std,23.836547,39.059755,54.464076,34.344035,18.549694,1.345313,84.717077,3.707460,6.300519,7.602393,3.905608,5397.406204,61.090353,58.405679,10.475552,10.488679,3.233663,26.869828,107.338675
min,12.000000,0.000000,59.000000,8.000000,0.000000,1.570000,102.000000,73.850000,6.020000,33.480000,5.320000,39.000000,0.200000,2.000000,2.100000,58.160000,36.000000,94.000000,196.000000
25%,57.000000,13.000000,217.500000,87.500000,16.000000,6.425000,406.500000,93.030000,21.480000,53.430000,14.310000,1566.000000,14.300000,50.000000,7.800000,71.530000,40.000000,132.000000,569.000000
50%,73.100000,44.200000,251.000000,109.800000,24.000000,7.230000,461.800000,94.460000,25.240000,58.070000,16.690000,4136.000000,32.400000,93.000000,11.100000,76.910000,43.000000,158.000000,631.000000
75%,88.000000,59.000000,291.000000,131.000000,32.000000,8.275000,535.000000,96.320000,28.780000,62.420000,19.060000,8757.000000,92.100000,134.000000,18.700000,83.190000,45.000000,175.000000,685.000000
max,156.000000,238.000000,388.000000,222.000000,120.000000,10.750000,661.000000,99.360000,43.720000,78.670000,29.320000,47298.000000,484.800000,431.000000,61.200000,118.530000,51.000000,191.000000,1149.000000

In [8]:
#再次查看缺失值情况
df.isnull().sum()

日期        0
REM时长     2
午睡时长      0
浅睡时长      2
深睡时长      2
清醒时长      0
夜间总睡眠     2
在床时间      2
睡眠效率      0
深睡比例      0
浅睡比例      0
快速眼动比例    0
是否午睡      0
星期        0
总步数       0
总消耗       0
总时长       0
每公里消耗     0
平均心率      0
最小心率      0
最大心率      0
记录条数      0
dtype: int64

In [9]:
#再次填充空缺值
df['REM时长']=df['REM时长'].fillna(df['REM时长'].mean())
df['REM时长']=df['REM时长'].round(1)

df['深睡时长']=df['深睡时长'].fillna(df['深睡时长'].mean())
df['深睡时长']=df['深睡时长'].round(1)

df['浅睡时长']=df['浅睡时长'].fillna(df['浅睡时长'].mean())
df['浅睡时长']=df['浅睡时长'].round(1)

df['夜间总睡眠']=df['夜间总睡眠'].fillna(df['夜间总睡眠'].mean())
df['夜间总睡眠']=df['夜间总睡眠'].round(2)

df['在床时间']=df['在床时间'].fillna(df['在床时间'].mean())
df['在床时间']=df['在床时间'].round(1)

In [10]:

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 305 entries, 0 to 304
Data columns (total 22 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   日期      305 non-null    str
 1   REM时长   305 non-null    float64
 2   午睡时长    305 non-null    float64
 3   浅睡时长    305 non-null    float64
 4   深睡时长    305 non-null    float64
 5   清醒时长    305 non-null    float64
 6   夜间总睡眠   305 non-null    float64
 7   在床时间    305 non-null    float64
 8   睡眠效率    305 non-null    float64
 9   深睡比例    305 non-null    float64
 10  浅睡比例    305 non-null    float64
 11  快速眼动比例  305 non-null    float64
 12  是否午睡    305 non-null    object
 13  星期      305 non-null    str
 14  总步数     305 non-null    int64
 15  总消耗     305 non-null    float64
 16  总时长     305 non-null    int64
 17  每公里消耗   305 non-null    float64
 18  平均心率    305 non-null    float64
 19  最小心率    305 non-null    int64
 20  最大心率    305 non-null    int64
 21  记录条数    305 non-null    int64
dtypes: float64(14), int64(5), object(1), str(2)
memory usage: 52.6+ KB

In [11]:
#导出清洗后的数据
df.to_csv('D:/DA/Huawei_Health_Analysis/DATA/processed/health_daily_summary_cleaned.csv',index=False,encoding='utf-8-sig')