In [2]:
%pip install pandas numpy

Requirement already satisfied: pandas in c:\users\30479\appdata\local\programs\python\python314\lib\site-packages (3.0.1)
Requirement already satisfied: numpy in c:\users\30479\appdata\local\programs\python\python314\lib\site-packages (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\30479\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\30479\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\30479\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [9]:
import pandas as pd
import numpy as np
df=pd.read_csv('D:/DA/Huawei_Sleep_Analysis/DATA/processed/health_daily_summary_cleaned.csv')

#检查缺失值情况
df.isnull().sum()

日期        0
REM时长     0
午睡时长      0
浅睡时长      0
深睡时长      0
清醒时长      0
夜间总睡眠     0
在床时间      0
睡眠效率      0
深睡比例      0
浅睡比例      0
快速眼动比例    0
是否午睡      0
星期        0
总步数       0
总消耗       0
总时长       0
每公里消耗     0
平均心率      0
最小心率      0
最大心率      0
记录条数      0
dtype: int64

In [ ]:
#合格睡眠率
normal=len(df[(df['夜间总睡眠']>7)&(df['夜间总睡眠']<9)&(df['深睡比例']>20)&(df['浅睡比例']<60)])
total=len(df)
normal_sleep_rate=round(normal/total,2)
print("合格睡眠率为：",normal_sleep_rate)

conscious=round(df['清醒时长'].mean()/(df['夜间总睡眠'].mean()*60),2)
print(f"平均清醒率为：{conscious}")

#基于我的个人数据，清醒占比正常但合格的睡眠占比偏低，需要做出调整。

合格睡眠率为： 0.33
平均清醒率为：0.06

In [ ]:
#入睡耗时对睡眠效率的影响
df['入睡耗时']=round(df['在床时间']/60,2)-df['夜间总睡眠']
平均睡眠效率=df['睡眠效率'].mean()
df['相对偏离百分率']=round((df['睡眠效率']-平均睡眠效率)/平均睡眠效率,2)
df[['日期','入睡耗时','睡眠效率','相对偏离百分率']].sort_values(by='入睡耗时',ascending=False).head(15).reset_index()

#结论：基于我的个人数据，入睡耗时过长会降低睡眠效率

    index          日期  入睡耗时   睡眠效率  相对偏离百分率
0     155  2025-11-22  1.83  76.34    -0.19
1     225  2026-01-31  1.82  80.60    -0.14
2      40  2025-07-30  1.60  83.59    -0.11
3     232  2026-02-07  1.48  83.76    -0.11
4     267  2026-03-14  1.48  84.47    -0.10
5     260  2026-03-07  1.39  83.56    -0.11
6     229  2026-02-04  1.33  86.53    -0.08
7     115  2025-10-13  1.30  85.84    -0.09
8     215  2026-01-21  1.27  87.48    -0.07
9     248  2026-02-23  1.26  86.36    -0.08
10    189  2025-12-26  1.24  73.85    -0.21
11    163  2025-11-30  1.23  76.73    -0.18
12    222  2026-01-28  1.23  87.91    -0.07
13    241  2026-02-16  1.18  83.79    -0.11
14    242  2026-02-17  1.14  87.29    -0.07

In [70]:
#午睡对夜间睡眠效率的影响
df['当晚睡眠效率']=df['睡眠效率'].shift(-1)
df['睡眠效率相对偏离']=round((df['当晚睡眠效率']-平均睡眠效率)/平均睡眠效率,2)
df[['日期','午睡时长','当晚睡眠效率','睡眠效率相对偏离']].sort_values(by='午睡时长',ascending=False).head(20)

#结论：基于我的个人数据，午睡过长几乎不会影响当晚的睡眠效率

             日期   午睡时长  当晚睡眠效率  睡眠效率相对偏离
82   2025-09-10  238.0   96.66      0.03
217  2026-01-23  215.0   95.91      0.02
93   2025-09-21  193.0   97.80      0.04
15   2025-07-05  173.0   97.68      0.04
134  2025-11-01  166.0   92.84     -0.01
174  2025-12-11  166.0   93.64     -0.00
57   2025-08-16  141.0   96.22      0.02
75   2025-09-03  132.0   94.94      0.01
246  2026-02-21  132.0   94.77      0.01
86   2025-09-14  128.0   96.13      0.02
175  2025-12-12  126.0   93.31     -0.01
121  2025-10-19  122.0   93.01     -0.01
156  2025-11-23  117.0   94.56      0.01
114  2025-10-12  113.0   85.84     -0.09
30   2025-07-20  113.0   91.29     -0.03
90   2025-09-18  112.0   91.15     -0.03
24   2025-07-14  111.0   96.54      0.03
100  2025-09-28  110.0   97.41      0.04
179  2025-12-16  110.0   92.52     -0.02
26   2025-07-16  109.0   91.53     -0.03

In [72]:
#长有氧运动对当晚深睡比例的影响
平均入睡耗时=df['入睡耗时'].mean()
df['当晚睡眠效率']=df['睡眠效率'].shift(-1)
df['当晚入睡耗时']=df['入睡耗时'].shift(-1)
df['入睡耗时相对偏离']=round((df['当晚入睡耗时']-平均入睡耗时)/平均入睡耗时,2)
df[['日期','平均心率','当晚入睡耗时','入睡耗时相对偏离','当晚睡眠效率','睡眠效率相对偏离']].sort_values(by='平均心率',ascending=False).head(20)

#结论：基于个人数据，高强度有氧运动对缩短当晚入睡耗时有促进作用，对当晚睡眠效率有利无害。
#其中78，106，183三天异常值经查证均为运动时间过晚，距离睡眠太近。

             日期    平均心率  当晚入睡耗时  入睡耗时相对偏离  当晚睡眠效率  睡眠效率相对偏离
52   2025-08-11  118.53    0.20     -0.57   97.36      0.04
261  2026-03-08  112.53    0.25     -0.46   97.06      0.03
67   2025-08-26  111.83    0.25     -0.46   96.73      0.03
78   2025-09-06  110.84    0.97      1.09   88.35     -0.06
10   2025-06-30  109.18    0.23     -0.50   97.82      0.04
56   2025-08-15  106.50    0.40     -0.14   94.58      0.01
23   2025-07-13  104.77    0.05     -0.89   99.36      0.06
105  2025-10-03   98.26    0.28     -0.40   94.44      0.00
106  2025-10-04   98.14    0.70      0.51   91.94     -0.02
163  2025-11-30   98.07    0.42     -0.09   95.84      0.02
40   2025-07-30   98.01    0.20     -0.57   97.30      0.03
49   2025-08-08   97.29    0.46     -0.01   94.04      0.00
183  2025-12-20   95.91    0.83      0.79   89.84     -0.04
155  2025-11-22   95.81    0.35     -0.24   95.80      0.02
58   2025-08-17   95.71    0.17     -0.63   98.03      0.04
104  2025-10-02   95.71    0.15     -0.68   97.63      0.04
230  2026-02-05   94.29    0.39     -0.16   96.08      0.02
1    2025-06-21   94.21    0.26     -0.44   97.08      0.03
108  2025-10-06   93.61    0.53      0.14   93.10     -0.01
132  2025-10-30   93.33    0.35     -0.24   94.89      0.01

In [67]:
round(df.groupby('星期').agg({'夜间总睡眠':'mean','深睡比例':'mean'}).sort_values(by='深睡比例',ascending=False).rename(columns={'夜间总睡眠':'均睡时长','深睡比例':'均深睡比例'}),2)

    均睡时长  均深睡比例
星期
周五  6.99  26.33
周日  7.46  25.91
周六  7.01  25.32
周二  7.15  25.09
周一  7.94  25.06
周四  6.96  24.70
周三  7.48  24.62

In [ ]:
df['当晚总睡眠']=df['夜间总睡眠'].shift(-1)
df.groupby('是否午睡').agg({'当晚总睡眠':'mean'}).rename(columns={'当晚总睡眠':'均睡时长'})

          均睡时长
是否午睡
False  7.35100
True   7.25568